---
- hosts: all
  sudo: yes

  vars:
    www_owner: fee
    www_group: apache
    drupal_deploy_key: >
      ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDiLORdcemdBOFV1rOIdSXFe9vkhdDLu5QyFG+4/C/rXE/A7eoJnnOEWPkvXgj0XBk3Dm9nbZRMfZkDsw1M16vkekp6JEjWp2e3RZztHq+iyDUCJfUbAwE1Q1+hrqHkFqg6s+fAOiwgUBFqO4kSAlyZh3sz734gODjgW2cHX8oe26EjEqHEI/CJygbc8zz2B15HqV73yrL/bVUvivhMu/bT3TqzQWP7DZ5C3TdHEod+e8QNQ+NlvkxspVQo/jqLovn5vsyAL26QkXSHZPf2iKw0FEPD8MVZOL1bFSwApxbb7ts4nceA+VctiQaCi9U6vN499Qg4V+uBTgtcUMTSNbdd homolog-taller-env@beanstalkapp.com
    drupal_deploy_script: "{{ drupal_path}}/../scripts/pull.sh"
    drupal_path: "/var/www/fee/docroot"
    drupal_www_owner: "{{ www_owner }}"
    drupal_www_group: "{{ www_group }}"
    drupal_version: homolog
    drupal_source: "https://{{ drupal_git_user }}:{{ drupal_git_pass }}@taller.git.beanstalkapp.com/fiesc-espaco-estudante.git"
    drupal_source_parent_level: ".."
    drupal_git_user: fiesc_espaco_estudante
    drupal_git_pass: f4avor1tebot4deploy
    drupal_db_dump: "http://qa-fiesc.fee.dropit.in/sites/default/files/bkp-qa.sql.gz"
    drupal_drush_remote_alias: "@fee.qa"
    drupal_db:
      driver: mysql
      user: "fee"
      password: "ZJD78OIK"
      database: "FEE_Homolog"
      host: "10.180.201.241"
      port: ""
      prefix: ""
    system_packages:
      - libselinux-python
      - libxml2
      - zlib
      - gcc
      - ruby
      - ruby-devel
      - mariadb
      - MySQL-python
    php_fpm_yum_packages:
      - php
      - php-fpm
      - php-cli
      - php-common
      - php-devel
      - php-gd
      - php-ldap
      - php-mbstring
      - php-mysql
      - php-pdo
      - php-pear
      - php-xml
      - php-xmlrpc
      - php-soap

  pre_tasks:
    - name: Include OS-specific variables.
      include_vars: "vars/{{ ansible_os_family }}.yaml"

    - name: "Installing dependencies (RedHat)."
      yum: >
        name={{ item }}
        enablerepo=rhel-7-server-debug-rpms,rhel-7-server-extras-debug-rpms,rhel-7-server-extras-rpms,rhel-7-server-extras-source-rpms,rhel-7-server-fastrack-debug-rpms,rhel-7-server-fastrack-rpms,rhel-7-server-fastrack-source-rpms,rhel-7-server-optional-debug-rpms,rhel-7-server-optional-fastrack-debug-rpms,rhel-7-server-optional-fastrack-rpms,rhel-7-server-optional-fastrack-source-rpms,rhel-7-server-optional-rpms,rhel-7-server-optional-source-rpms,rhel-7-server-rh-common-debug-rpms,rhel-7-server-rh-common-rpms,rhel-7-server-rh-common-source-rpms,rhel-7-server-rhn-tools-debug-rpms,rhel-7-server-rhn-tools-rpms,rhel-7-server-rhn-tools-source-rpms,rhel-7-server-rpms,rhel-7-server-supplementary-debug-rpms,rhel-7-server-supplementary-rpms,rhel-7-server-supplementary-source-rpms,rhel-7-server-thirdparty-oracle-java-rpms,rhel-7-server-thirdparty-oracle-java-source-rpms,rhel-7-server-v2vwin-1-debug-rpms,rhel-7-server-v2vwin-1-rpms,rhel-7-server-v2vwin-1-source-rpms
        state=latest
      with_items: system_packages
      when: ansible_os_family == 'RedHat'
      tags:
        - system

    - name: "Add ruby gems dependency manager (bundler)."
      gem: >
        name=bundler
        user_install=no
      tags:
        - system

    - name: "Create www's group group."
      group: "name={{ www_group }}"
      tags:
        - user

    - name: "Create www's owner user."
      user: >
        name={{ www_owner }}
        group={{ www_group }}
        shell=/bin/bash
        append=yes
      tags:
        - user

    - name: "Generate www's owner ssh key."
      user: >
        name={{ www_owner }}
        generate_ssh_key=yes
        ssh_key_bits=2048
        ssh_key_file=/home/{{ www_owner }}/.ssh/id_rsa
      tags:
        - user

  roles:
    - role: geerlingguy.git
      git_packages:
        - git
      tags:
        - git

    - role: geerlingguy.apache
      apache_vhosts:
        # Additional properties: 'serveradmin, extra_parameters'.
        - servername: "estudante.sc.senai.br"
          documentroot: "{{ drupal_path }}"
      tags:
        - webserver

    # Install and configure: PHP-FPM with 3 pools.
    - role: nbz4live.php-fpm
      php_fpm_config:
        - option: "error_log"
          section: "global"
          value: "/var/log/php-fpm/php5-fpm.log"
        - option: "emergency_restart_threshold"
          section: "global"
          value: "10"
        - option: "emergency_restart_interval"
          section: "global"
          value: "1m"
        - option: "process_control_timeout"
          section: "global"
          value: "5"
        - option: "daemonize"
          section: "global"
          value: "no"

      php_fpm_ini:
        - option: "memory_limit"
          section: "PHP"
          value: "512M"
        - option: "engine"
          section: "PHP"
          value: "1"
        - option: "error_reporting"
          section: "PHP"
          value: "E_ALL & ~E_DEPRECATED & ~E_STRICT"
        - option: "ldap.max_links"
          section: "ldap"
          value: "1"
        - option: "max_execution_time"
          section: "PHP"
          value: "60"
        - option: "upload_max_filesize"
          section: "PHP"
          value: "64M"
        - option: "date.timezone"
          section: "Date"
          value: "America/Sao_Paulo"
          # APC related configuration.
        - option: "apc.shm_size"
          section: "APC"
          value: "96M"
        - option: "apc.shm_segments"
          section: "APC"
          value: "1"
        - option: "apc.num_files_hint"
          section: "APC"
          value: "2048"
        - option: "apc.user_entries_hint"
          section: "APC"
          value: "4096"
        - option: "apc.ttl"
          section: "APC"
          value: "7200"
        - option: "apc.use_request_time"
          section: "APC"
          value: "1"
        - option: "apc.user_ttl"
          section: "APC"
          value: "7200"
        - option: "apc.gc_ttl"
          section: "APC"
          value: "3600"
        - option: "apc.mmap_file_mask"
          section: "APC"
          value: "/tmp/apc.XXXXXX"
        - option: "apc.file_update_protection"
          section: "APC"
          value: "2"
        - option: "apc.enable_cli"
          section: "APC"
          value: "1"
        - option: "apc.max_file_size"
          section: "APC"
          value: "1M"
        - option: "apc.stat"
          section: "APC"
          value: "1"
        - option: "apc.stat_ctime"
          section: "APC"
          value: "0"
        - option: "apc.canonicalize"
          section: "APC"
          value: "0"
        - option: "apc.write_lock"
          section: "APC"
          value: "1"
        - option: "apc.report_autofilter"
          section: "APC"
          value: "0"
        - option: "apc.rfc1867"
          section: "APC"
          value: "1"
        - option: "apc.rfc1867_prefix"
          section: "APC"
          value: "upload_"
        - option: "apc.rfc1867_name"
          section: "APC"
          value: "APC_UPLOAD_PROGRESS"
        - option: "apc.rfc1867_freq"
          section: "APC"
          value: "0"
        - option: "apc.rfc1867_ttl"
          section: "APC"
          value: "3600"
        - option: "apc.include_once_override"
          section: "APC"
          value: "0"
        - option: "apc.lazy_classes"
          section: "APC"
          value: "0"
        - option: "apc.lazy_functions"
          section: "APC"
          value: "0"
        - option: "apc.coredump_unmap"
          section: "APC"
          value: "0"
        - option: "apc.file_md5"
          section: "APC"
          value: "0"

      php_fpm_pools:
        - name: www0
          listen: /var/run/php-fpm.sock
          user: "{{ www_owner }}"
          group: "{{ www_group }}"
          listen.owner: "{{ www_owner }}"
          listen.group: "{{ www_group }}"
          pm: dynamic
          pm.max_children: 5
          pm.start_servers: 2
          pm.min_spare_servers: 1
          pm.max_spare_servers: 3
          chdir: /

        - name: www1
          listen: /var/run/php-fpm-zwei.sock
          user: "{{ www_owner }}"
          group: "{{ www_group }}"
          listen.owner: "{{ www_owner }}"
          listen.group: "{{ www_group }}"
          pm: dynamic
          pm.max_children: 5
          pm.start_servers: 2
          pm.min_spare_servers: 1
          pm.max_spare_servers: 3
          chdir: /

        - name: www-bkp
          listen: /var/run/php-fpm-bkp.sock
          user: "{{ www_owner }}"
          group: "{{ www_group }}"
          listen.owner: "{{ www_owner }}"
          listen.group: "{{ www_group }}"
          pm: dynamic
          pm.max_children: 5
          pm.start_servers: 2
          pm.min_spare_servers: 1
          pm.max_spare_servers: 3
          chdir: /
      tags:
        - php

    - role: revagomes.php-pecl
      php_pecl_extensions:
        - apc
      tags:
        - php

    - geerlingguy.composer
    - role: geerlingguy.drush
      drush_version: 6.x
      tags:
        - drupal

    - role: taller.fiesc-drupal
      tags:
        - drupal

  tasks:
    - name: "Add the deploy key to authorized_keys file."
      authorized_key: >
        user={{ www_owner }}
        key="{{ deploy_key }}"

    - name: "Set permissions for the /var/www directory."
      file: >
        path=/var/www
        mode=6775
        owner={{ www_owner }}
        group={{ www_group }}
        state=directory

    # sudo iptables -I INPUT 4 -p tcp -m state --state NEW -m tcp --dport 80 -j ACCEPT
    - name: "Expose port 80 to the world."
      command: iptables -I INPUT 4 -p tcp -m state --state NEW -m tcp --dport 80 -j ACCEPT
      # ufw: rule=allow port=80 proto=tcp
