---
# Create the .drush dir.
- name: "Ensure Drush configuration folder exists."
  file:
    path: "/home/{{ www_owner }}/.drush"
    state: directory
  sudo: no

# Update drushrc.php file.
- name: "Update drushrc.php file."
  template: >
    src=drushrc.php.j2
    dest="/home/{{ www_owner }}/.drush/drushrc.php"

# Sync files via drush.
- name: "Sync files using drush aliases."
  shell: >
    /usr/local/bin/drush -y rsync {{ drupal_drush_remote_alias }}:%files/ @self:%files
    chdir={{ drupal_path }}
  sudo: yes
  sudo_user: "{{ drupal_www_owner }}"
  when: drupal_drush_remote_alias | match("^@.+")
