---


# Assemble the local settings.

# - name: "Create directory with local settings."
#   file: >
#     path={{ drupal_path }}/sites/default/settings.d
#     state=directory

# - name: "Create local settings.local.php file with local info like database."
#   assemble: >
#     src={{ drupal_path }}/sites/default/settings.d
#     mode=644

- name: "Database local settings."
  template: >
    src=settings.db.j2
    dest={{ drupal_path }}/sites/default/settings.local.php

# Insert <?php tag.
- lineinfile: >
    line="<?php"
    state=present
    insertafter=BOF
    dest={{ drupal_path }}/sites/default/settings.local.php
  when: drupal_db.database != "" and drupal_db.host != ""

# Makes the include of local settings file,
# in case it's a new installation.
- name: "Include the local settings file into the settings.php."
  lineinfile: >
    line="include 'settings.local.php';"
    state=present
    insertafter=EOF
    dest={{ drupal_path }}/sites/default/settings.php
  when: >
    drupal_new_installation_result is defined and drupal_new_installation_result.rc == 0
