---
# TODO: Try to call the vars_file just once
- hosts: all
  sudo: yes

  pre_tasks:
    - include: tasks/init.yml

- hosts: solr
  sudo: yes

  vars_files:
    - ./config.yml

  roles:
    - geerlingguy.java
    - geerlingguy.tomcat6
    - geerlingguy.solr

- hosts: test
  sudo: yes

  vars_files:
    - ./config.yml

  pre_tasks:
    - name: Install Xvfb for headless tests
      apt:
        name: xvfb
        state: present

  roles:
    - role: g-div.nvm
      nvm_user: "{{ app_user }}"
      nvm_version: "v0.24.0"
      nvm_node_version: "{{ node_version }}"
      nvm_profile_file: "/home/{{ app_user }}/.profile"
      nvm_packages:
        - protractor
        - jasmine-spec-reporter

    - role: geerlingguy.java

- hosts: database
  sudo: yes

  vars_files:
    - ./config.yml

  roles:
    - role: geerlingguy.mysql
      mysql_databases:
       - name: "{{ drupal_mysql_database }}"
         encoding: utf8
         collation: utf8_unicode_ci
      mysql_users:
       - name: "{{ drupal_mysql_drupal_user }}"
         host: "%"
         password: "{{ drupal_mysql_drupal_password }}"
         priv: "{{ drupal_mysql_database }}.*:ALL"

- hosts: drupal
  sudo: yes

  vars_files:
    - ./config.yml

  pre_tasks:

    - name: Install mailutils so Drupal can send emails.
      apt: name=mailutils state=present

    - name: Create project folder.
      file: >
        path={{ project_path }}
        mode=6755
        owner={{ drupal_www_owner }}
        group={{ drupal_www_group }}
        state=directory
      when: skip_clone == false and drupal_source == ''

    - name: Install dependencies.
      apt: "pkg={{item}}"
      with_items:
        - sendmail

  roles:
    - role: geerlingguy.git
      git_packages:
        - git
        - git-flow

    # Install: Nginx with extras.
    - role: jdauphant.nginx
      nginx_ubuntu_pkg:
        - python-selinux
        - nginx-extras

    # Install and configure: PHP-FPM with 3 pools.
    - role: nbz4live.php-fpm
      php_fpm_apt_packages:
        - php5-fpm
        - php5-cli
        - php5-gd
        - php5-mysql
        - php5-mcrypt
        - php5-dev
        - php-pear
        - php-apc
        - php5-curl
        - php-mail

      php_fpm_config:
        - option: "emergency_restart_threshold"
          section: "global"
          value: "10"
        - option: "emergency_restart_interval"
          section: "global"
          value: "1m"
        - option: "process_control_timeout"
          section: "global"
          value: "5"
        - option: "daemonize"
          section: "global"
          value: "no"

      php_fpm_ini:
        - option: "memory_limit"
          section: "PHP"
          value: "512M"
        - option: "engine"
          section: "PHP"
          value: "1"
        - option: "error_reporting"
          section: "PHP"
          value: "E_ALL & ~E_DEPRECATED & ~E_STRICT"
        - option: "ldap.max_links"
          section: "ldap"
          value: "1"
        - option: "max_execution_time"
          section: "PHP"
          value: "60"
        - option: "upload_max_filesize"
          section: "PHP"
          value: "64M"
        - option: "date.timezone"
          section: "Date"
          value: "America/Sao_Paulo"
          # APC related configuration.
        - option: "apc.shm_size"
          section: "APC"
          value: "96M"
        - option: "apc.shm_segments"
          section: "APC"
          value: "1"
        - option: "apc.num_files_hint"
          section: "APC"
          value: "2048"
        - option: "apc.user_entries_hint"
          section: "APC"
          value: "4096"
        - option: "apc.ttl"
          section: "APC"
          value: "7200"
        - option: "apc.use_request_time"
          section: "APC"
          value: "1"
        - option: "apc.user_ttl"
          section: "APC"
          value: "7200"
        - option: "apc.gc_ttl"
          section: "APC"
          value: "3600"
        - option: "apc.mmap_file_mask"
          section: "APC"
          value: "/tmp/apc.XXXXXX"
        - option: "apc.file_update_protection"
          section: "APC"
          value: "2"
        - option: "apc.enable_cli"
          section: "APC"
          value: "1"
        - option: "apc.max_file_size"
          section: "APC"
          value: "1M"
        - option: "apc.stat"
          section: "APC"
          value: "1"
        - option: "apc.stat_ctime"
          section: "APC"
          value: "0"
        - option: "apc.canonicalize"
          section: "APC"
          value: "0"
        - option: "apc.write_lock"
          section: "APC"
          value: "1"
        - option: "apc.report_autofilter"
          section: "APC"
          value: "0"
        - option: "apc.rfc1867"
          section: "APC"
          value: "1"
        - option: "apc.rfc1867_prefix"
          section: "APC"
          value: "upload_"
        - option: "apc.rfc1867_name"
          section: "APC"
          value: "APC_UPLOAD_PROGRESS"
        - option: "apc.rfc1867_freq"
          section: "APC"
          value: "0"
        - option: "apc.rfc1867_ttl"
          section: "APC"
          value: "3600"
        - option: "apc.include_once_override"
          section: "APC"
          value: "0"
        - option: "apc.lazy_classes"
          section: "APC"
          value: "0"
        - option: "apc.lazy_functions"
          section: "APC"
          value: "0"
        - option: "apc.coredump_unmap"
          section: "APC"
          value: "0"
        - option: "apc.file_md5"
          section: "APC"
          value: "0"

      php_fpm_pools:
        - name: www0
          listen: /var/run/php-fpm.sock
          user: "{{ www_owner }}"
          group: "{{ www_group }}"
          listen.owner: "{{ www_owner }}"
          listen.group: "{{ www_group }}"
          pm: dynamic
          pm.max_children: 5
          pm.start_servers: 2
          pm.min_spare_servers: 1
          pm.max_spare_servers: 3
          chdir: /

        - name: www1
          listen: /var/run/php-fpm-zwei.sock
          user: "{{ www_owner }}"
          group: "{{ www_group }}"
          listen.owner: "{{ www_owner }}"
          listen.group: "{{ www_group }}"
          pm: dynamic
          pm.max_children: 5
          pm.start_servers: 2
          pm.min_spare_servers: 1
          pm.max_spare_servers: 3
          chdir: /

        - name: www-bkp
          listen: /var/run/php-fpm-bkp.sock
          user: "{{ www_owner }}"
          group: "{{ www_group }}"
          listen.owner: "{{ www_owner }}"
          listen.group: "{{ www_group }}"
          pm: dynamic
          pm.max_children: 5
          pm.start_servers: 2
          pm.min_spare_servers: 1
          pm.max_spare_servers: 3
          chdir: /

    # Install: Perusio's Nginx configurations.
    - role: pbuyle.nginx-drupal
      nginx_drupal_aio: false
      nginx_drupal_use_drush: true
      nginx_drupal_microcache: false
      nginx_drupal_flv_streaming: false
      nginx_drupal_mp4_streaming: false
      nginx_drupal_x_frame_options: "SAMEORIGIN"
      nginx_drupal_http_pre_params: "{{ nginx_http_params }}"
      nginx_drupal_http_core:
        client_max_body_size: "10m"
        ssl_session_cache: true
      nginx_drupal_upstream_servers:
        - "unix:/var/run/php-fpm.sock"
        - "unix:/var/run/php-fpm-zwei.sock"
      nginx_drupal_upstream_backup_servers:
        - "unix:/var/run/php-fpm-bkp.sock"
      nginx_drupal_sites:
        - file_name: default
          root: "{{ drupal_path_dir }}"
          http:
            port: 80
          server_name: "{{ vagrant_hostname }}"
          default: true
          not_allowed_methods: none

    # Install: PHP Composer.
    - role: kosssi.composer
      composer_home_owner: "{{ www_owner }}"
      composer_home_group: "{{ www_owner }}"
      composer_home_path: "/opt/composer"
      composer_global_packages: {}
      composer_path_env: true

    # Install: Drush.
    - role: geerlingguy.drush

    # Install: Drupal Project.
    - role: taller.drupal
      drupal_path: "{{ drupal_path_dir }}"
      drupal_www_owner: "{{ www_owner }}"
      drupal_db:
        driver: mysql
        user: "{{ drupal_mysql_drupal_user }}"
        password: "{{ drupal_mysql_drupal_password }}"
        database: "{{ drupal_mysql_database }}"
        host: "localhost"
        port: ""
        prefix: ""

  tasks:
    - include: tasks/ruby.yml
    - include: tasks/drush.yml
    - include: tasks/extras.yml

    - name: Install Xdebug for PHP.
      apt: pkg=php5-xdebug
      when: enable_debug == 'yes'

    - name: Set LC_ALL system variable.
      shell: >
        echo 'export LC_ALL=en_US.utf8' >> ~/.bashrc
      tags:
        - system

    - name: Restart Nginx and PHP-FPM services.
      service: "name={{ item }} state=restarted"
      with_items:
        - nginx
        - php5-fpm
      ignore_errors: true
