---
drupal_www_owner: taller
drupal_www_group: www-data
php_fpm_apt_packages:
  - php5-fpm
  - php5-cli
  - php5-dev
  - php5-common
  - php5-gd
  - php5-mysql
  - php5-mcrypt
  - php-pear
  - php-apc
  - php5-curl
  - php-mail
  - php5-xmlrpc
  - php-soap
