---
# Vagrant hostname and IP configuration.
vagrant_hostname: fee.dev
vagrant_ip: 10.10.10.1
vagrant_machine_name: :fee-dev
vagrant_base_box: "ubuntu/trusty64"
vagrant_environment: "local"

# A list of synced folders, with the keys 'local_path', 'destination', and 'id'.
vagrant_synced_folders:
  - local_path: ~/Sites/drupal
    destination: /drupal
    excluded_paths: [".git/"]
    id: drupal
    type: rsync

# Memory and CPU to use for this VM.
vagrant_memory: 1024
vagrant_cpus: 2
