---
www_group: www-data
drupal_www_owner: fee
drupal_www_group: www-data
system_packages:
  - libxml2
  - zlib1g
  - libssl-dev
  - libreadline-gplv2-dev
  - nfs-common
  - mysql-client
  # Need to add 2 versions from same repo to make update-alternatives work
  - ruby2.0
  - ruby2.2
php_fpm_apt_packages:
  - php5-fpm
  - php5-cli
  - php5-dev
  - php5-common
  - php5-gd
  - php5-mysql
  - php5-mcrypt
  - php-pear
  - php-apc
  - php5-curl
  - php-mail
  - php5-xmlrpc
  - php-soap
  - php-apc
php_fpm_config:
  - option: "error_log"
    section: "global"
    value: "/var/log/php5-fpm.log"
  - option: "emergency_restart_threshold"
    section: "global"
    value: "10"
  - option: "emergency_restart_interval"
    section: "global"
    value: "1m"
  - option: "process_control_timeout"
    section: "global"
    value: "5"
  - option: "daemonize"
    section: "global"
    value: "no"
php_pecl_extensions: []
